### ISSUE TITLE
Use English?

### ISSUE THREAD

**Issue by bruno-ds** [Ousret/hermes#2]
Hello,
Congratulations for your project.
Maybe you could write the readme/docs/code in English in order to open you project to a broader audience?

I realize that it take some more time, but once you get used to it, your flow isn't impact no more :)

**Comment by Ousret** [comment]
Hi,

Thank you for the feedback. By looking at my others projects you can tell that this one is different clearly. This project can be translated, I hope it would. Maybe, propose a PR in order to start translating ? :+1: 

I have no plan in near future to translate it myself. But the project is ready to be translated, beside docs written in markdown, the python package have a i18n pot file ready to be translated.

I hope this project is going to be used even if actually written in french. And maybe someone will participate in it.
